MinecraftForge/EventBus

- src/main/java/net/minecraftforge/eventbus/EventBus.java
- src/main/java/net/minecraftforge/eventbus/api/IEventBus.java
- src/test/java/net/minecraftforge/eventbus/test/WeirdGenericTests.java
A simple fix, the root problem goes back to [2015](https://github.com/MinecraftForge/MinecraftForge/issues/2097).
Just change the `GenericEvent` type parameter to `<? extends F>` and all is well. See the new test for an example of why this is necessary.
> Fix generic listeners not accepting nested generics

- src/main/java/net/minecraftforge/eventbus/ASMEventHandler.java
When the generic type of a generic event is, in itself, generic, the `filter` ends up being a `ParameterizedType` which will never `==` the raw type of the event. So simply discard that generic information, it would never be useful in practice anyways as no event impl could provide a usable parameterized type.
> Fix generic event filter failing when nested type is itself generic

- build.gradle
- src/jmh/java/net/minecraftforge/eventbus/benchmarks/EventBusBenchmark.java
- src/main/java/net/minecraftforge/eventbus/EventBus.java
- src/testJars/java/net/minecraftforge/eventbus/benchmarks/compiled/CancelableEvent.java
- src/testJars/java/net/minecraftforge/eventbus/benchmarks/compiled/ResultEvent.java
- src/testJars/java/net/minecraftforge/eventbus/benchmarks/compiled/SimpleEvent.java
- src/testJars/java/net/minecraftforge/eventbus/benchmarks/compiled/SubscriberDynamic.java
- src/testJars/java/net/minecraftforge/eventbus/benchmarks/compiled/SubscriberLambda.java
- src/testJars/java/net/minecraftforge/eventbus/benchmarks/compiled/SubscriberStatic.java
This adds some microbenchmarks, similar to modlauncher.
The changes in EventBus should make the code do the same, but much faster.
Before:
```
Benchmark                             Mode  Cnt  Score   Error  Units
EventBusBenchmark.testDynamic         avgt    9  0,009 ± 0,002  us/op
EventBusBenchmark.testDynamic:·stack  avgt         NaN            ---
EventBusBenchmark.testLambda          avgt    9  0,246 ± 0,008  us/op
EventBusBenchmark.testLambda:·stack   avgt         NaN            ---
EventBusBenchmark.testStatic          avgt    9  0,035 ± 0,001  us/op
EventBusBenchmark.testStatic:·stack   avgt         NaN            ---
```
After:
```
Benchmark                             Mode  Cnt  Score    Error  Units
EventBusBenchmark.testDynamic         avgt    9  0,009 ±  0,001  us/op …
```
> Add microbenchmark and improve performance of lambda event handler

- src/main/java/net/minecraftforge/eventbus/ListenerList.java
Following the pattern set forth in `extendMasterList`, this aims to synchronize all iteration and modification of `allLists` on the class lock. Should fix potential CMEs when unregistering listeners and other (rarer) actions such as constructing a new EventBus.
> Synchronize all iteration/modification of ListenerList.allLists

- src/main/java/net/minecraftforge/eventbus/EventBus.java
This lets exceptions pass through unaltered, so things like `EnhancedRuntimeException` and `ReportedException` can pass through.
It's legal to rethrow the exception here because it is not a checked exception from `IEventListener#invoke`.
> Avoid wrapping exceptions thrown by event listeners

- src/test/java/net/minecraftforge/eventbus/test/ParallelEventTest.java
In an effort to see if https://github.com/MinecraftForge/MinecraftForge/issues/5708 is related to EventBus, I created a new test that registers and posts events parallel on the event bus.
This currently fails almost always on multiple thread that access one bus, I'm still searching where it happens, but when switching `parallelStream` to a regular `stream` it works, so there is a race condition somewhere..
> Add test for parallel event bus testing

- src/main/java/net/minecraftforge/eventbus/EventSubclassTransformer.java
- src/main/java/net/minecraftforge/eventbus/Names.java
- src/main/java/net/minecraftforge/eventbus/api/Event.java
- src/test/java/net/minecraftforge/eventbus/test/AbstractEventListenerTest.java
Update EventSubclassTransformer to use static initialization for the synthetic LISTENER_LIST field.
This is guaranteed to be thread safe by the Java spec: https://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.4.2
Pushed as a PR so that others can test it before I pushed.
And because I am running into a phantom test failure related to classloader leaking. It only happens in eclipse junit debug mode.
However gradle passes all tests fine.
Things to note:
I'm pretty sure technically we can remove getParentListenerList completely. As the parent list is managed in the helper now. And no code, not even the transformed code calls this.
Same goes for setup() which was added as a necessity for the listener list creation. But now that we use `<clinit>` we don't need it anymore.
> Update EventSubclassTransformer to use static initialization

- src/main/java/net/minecraftforge/eventbus/ListenerList.java
> Fix race condition in ListenerList.resize(int)

- src/main/java/net/minecraftforge/eventbus/EventAccessTransformer.java
The method access flags were updated twice instead of updating the class access flags. This also caused the method having invalid flag combinations, e.g. `ABSTRACT` (`ACC_ABSTRACT` on classes) and `SYNCHRONIZED` (`ACC_SUPER` on classes). This leads to startup errors (i.e. java.lang.ClassFormatError when trying to load the class file later).
> Properly update classNode access flag

- src/main/java/net/minecraftforge/eventbus/api/IEventBus.java
This PR adds a small helper method that allows for cleaner usage of posted event data.
Before:
```java
var event = new MyEvent();
bus.post(event);
if (event.getResult().isAllowed()) {
// do thing
}
```
After:
```java
if (bus.fire(new MyEvent()).getResult().isAllowed()) {
// do thing
}
```
> Add `IEventBus#fire` to return the posted event object

- eventbus-test-jar/src/main/java/net/minecraftforge/eventbus/testjar/benchmarks/ClassFactory.java
- eventbus-test-jar/src/main/java/net/minecraftforge/eventbus/testjar/subscribers/SubscriberDynamic.java
- eventbus-test-jar/src/main/java/net/minecraftforge/eventbus/testjar/subscribers/SubscriberLambda.java
- eventbus-test-jar/src/main/java/net/minecraftforge/eventbus/testjar/subscribers/SubscriberStatic.java
This allows ClassFactory to work on future JDKs without needing adjustments to account for internal changes.
> Remove reliance on JDK internals in ClassFactory

- src/main/java/net/minecraftforge/eventbus/EventBusEngine.java
We already filter out most Vanilla Minecraft classes, but we've been missing some since Blaze3D open sourcing and the like.
> Add `startsWith("com.mojang.")` to transform blacklist

- src/main/java/net/minecraftforge/eventbus/ASMEventHandler.java
- src/main/java/net/minecraftforge/eventbus/EventBus.java
- src/main/java/net/minecraftforge/eventbus/ListenerList.java
- Make storing nulls in `ListenerListInst` a no-op
- Skip now-unneeded null checks in `EventBus` and `ASMEventHandler`
- Some trivial cleanup to `ASMEventHandler`'s constructor, make the `filter` field final
> Simplify listener class checks in posting hot-path

- src/main/java/net/minecraftforge/eventbus/internal/BusGroupImpl.java
Fixes the thread-safety issue mentioned in https://github.com/MinecraftForge/MinecraftForge-Experimental/pull/1.
Basically a version of 6.2's [CacheConcurrent#computeIfAbsent](https://github.com/MinecraftForge/EventBus/blob/bb81df72d7e2b4315fabc90cf9fe8f3a7388ffed/src/main/java/net/minecraftforge/eventbus/CacheConcurrent.java#L31) without the finalizer param.
> [7.0-beta] Fix recursive update

- eventbus-test-jar/src/main/java/net/minecraftforge/eventbus/testjar/benchmarks/ModLauncherBenchmarks.java
- eventbus-test-jar/src/main/java/net/minecraftforge/eventbus/testjar/benchmarks/NoLoaderBenchmarks.java
- src/main/java/net/minecraftforge/eventbus/BusBuilderImpl.java
- src/main/java/net/minecraftforge/eventbus/EventBus.java
- src/main/java/net/minecraftforge/eventbus/ListenerList.java
- src/main/java/net/minecraftforge/eventbus/api/BusBuilder.java
Supersedes #66.
This allows for phase tracking to only apply to the requested phases, rather than an 'all or nothing' like previously.
Will run the benchmarks later when I have time.
> [6.2.x] Add support for fine-tuned phase tracking

- src/main/java/net/minecraftforge/eventbus/internal/AbstractEventBusImpl.java
This PR saves some more memory when calling `dispose()` and `trim()` - especially for `non-sealed`, non-`final` `InheritableEvent`s with at least one child - in that case, the list of children would be 10 elements long (the default size of `new ArrayList<>()` after adding an element).
https://github.com/MinecraftForge/EventBus/blob/b16bcf7a1316f3c17fb4c6e9607837f84c16eb7f/src/main/java/net/minecraftforge/eventbus/internal/AbstractEventBusImpl.java#L49-L62
> Account for child `EventBus`es in `dispose()` and `trim()`

- build.gradle
- buildSrc/build.gradle
- buildSrc/settings.gradle
- buildSrc/src/main/groovy/ArchiveJfr.groovy
- eventbus-jmh/build.gradle
- eventbus-test-jar/build.gradle
- eventbus-test/build.gradle
- settings.gradle
Name entails. Gradle should no longer complain or generate problem reports with this project.
I've split each part of this into its own commit, each with its own justification in its commit description.
> Cleanup Gradle buildscripts and fix deprecations

- eventbus-test/src/test/java/net/minecraftforge/eventbus/test/IndividualEventListenerTests.java
- src/main/java/net/minecraftforge/eventbus/internal/Constants.java
- src/main/java/net/minecraftforge/eventbus/internal/InvokerFactory.java
- src/main/java/net/minecraftforge/eventbus/internal/InvokerFactoryUtils.java
If the event is cancellable but all listeners are consumers, the invoker optimisation strategy would previously bail out to using the wrapped predicates if alwaysCancelling listeners were present. The listener elimination optimisation would still apply, but redundant wrapping remained.
Now, alwaysCancelling listeners are properly accounted for in this case, combining the benefits of eliminating non-monitoring listeners after them with also unwrapping to branchless consumer calls in the built invoker.
The logic for the `eventbus.experimental.unwrapCancellableThreshold` system property remains unchanged. A future PR may adjust this so that the threshold is checked *after* listener elimination, I haven't done this yet as I'd like to first ensure the invoker build times aren't too badly …
> Enhance alwaysCancelling listener awareness in invoker optimisation strategy

- README.md
- eventbus-test/build.gradle
- eventbus-test/src/test/java/module-info.java
- eventbus-test/src/test/java/net/minecraftforge/eventbus/test/BulkEventListenerTests.java
- eventbus-test/src/test/java/net/minecraftforge/eventbus/test/compiletime/CompileTestHelper.java
- eventbus-test/src/test/java/net/minecraftforge/eventbus/test/compiletime/EventBusValidatorTests.java
- eventbus-test/src/test/java/net/minecraftforge/eventbus/test/compiletime/EventTypeValidatorTests.java
- eventbus-test/src/test/java/net/minecraftforge/eventbus/test/compiletime/SubscribeEventValidatorTests.java
- eventbus-validator/build.gradle
- eventbus-validator/src/main/java/module-info.java
- eventbus-validator/src/main/java/net/minecraftforge/eventbus/validator/AbstractValidator.java
- eventbus-validator/src/main/java/net/minecraftforge/eventbus/validator/EventBusValidator.java
- eventbus-validator/src/main/java/net/minecraftforge/eventbus/validator/EventTypeValidator.java
- eventbus-validator/src/main/java/net/minecraftforge/eventbus/validator/SubscribeEventValidator.java
- eventbus-validator/src/main/resources/META-INF/services/javax.annotation.processing.Processor
- settings.gradle
- src/main/java/module-info.java
- src/main/java/net/minecraftforge/eventbus/internal/BusGroupImpl.java
- src/main/java/net/minecraftforge/eventbus/internal/Constants.java
- src/main/java/net/minecraftforge/eventbus/internal/EventListenerFactory.java
This PR enhances validation of API usages by library users and improves startup times.
- Introduced `eventbus.api.strictRuntimeChecks` and `eventbus.api.strictBusCreationChecks` system properties
- Added runtime check for incorrect `InheritableEvent`  usages
- Introduced a new annotation processor that shifts strict runtime checks to compile-time
- Moved some runtime checks to only apply in strict mode, relying instead on the compile-time validation and runtime opt-ins for faster startup
- Added documentation about the new behaviour in the [readme](https://github.com/PaintNinja/EventBus/blob/7.0-compile-time-validation/README.md#validation) and initial work on compile-time tests
- Some runtime checks are now opt-in with the system properties mentioned above and no longer apply by default. …
> [7.0] Introduce compile-time validation, enhance strict runtime checks

- src/main/java/net/minecraftforge/eventbus/api/Event.java
To avoid a breaking change, this new method is not final, as doing so could break any events that added their own cancel method.
> [6.2] Add Event#cancel() convenience method
